### ISSUE TITLE
error running worker in Windows

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#206]
I'm getting the error below when trying to launch the worker in Windows:
"Signals are not really supported on Windows"

I am using Windows 10, 64 bit.   I tried python 3.6 and python 3.5.  

Any ideas?  Thanks!

![image](https://user-images.githubusercontent.com/839047/27516943-e3b11940-5988-11e7-96e1-87a923a88414.png)

Here is the output of `pip freeze`:

> R:\blender\flamenco_v2\worker\worker_dellnavi\bin>pip freeze
> attrs==17.2.0
> certifi==2017.4.17
> chardet==3.0.4
> flamenco-worker==2.0.6b1
> idna==2.5
> requests==2.18.1
> urllib3==1.21.1
>
> R:\blender\flamenco_v2\worker\worker_dellnavi\bin>

--Shaun

**Comment by sybrenstuvel** [comment]
In `flamenco_worker\cli.py`, can you take out the following lines?

```
    from . import patch_asyncio
    patch_asyncio.patch_asyncio()
```

If the worker runs fine then, I'll release a version where patching asyncio is only done on non-Windows platforms.

**Comment by binarypearl** [comment]
After commenting out those 2 lines I get:
```
R:\blender\flamenco_v2\worker\worker_dellnavi>python .\bin\flamenco-worker
Traceback (most recent call last):
  File ".\bin\flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 90, in main
    signal.signal(signal.SIGUSR1, asyncio_report_tasks)
AttributeError: module 'signal' has no attribute 'SIGUSR1'

R:\blender\flamenco_v2\worker\worker_dellnavi>
```

I then commented out line 90 (signal.signal(signal.SIGUSR1, asyncio_report_tasks)) and got:
```
R:\blender\flamenco_v2\worker\worker_dellnavi>python .\bin\flamenco-worker
2017-06-27 06:41:05,283     INFO flamenco_worker.worker.FlamencoWorker Starting up
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1048, in emit
    self.stream = self._open()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\tmp\\flamenco-worker.log'
Call stack:
  File ".\bin\flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 97, in main
    loop.run_until_complete(fworker.startup())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1424, in _run_once
    handle._run()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 126, in _run
    self._callback(*self._args)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 108, in startup
    self._log.info('Starting up')
Message: 'Starting up'
Arguments: ()
2017-06-27 06:41:05,292     INFO flamenco_worker.worker.FlamencoWorker Registering at manager
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1048, in emit
    self.stream = self._open()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\tmp\\flamenco-worker.log'
Call stack:
  File ".\bin\flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 97, in main
    loop.run_until_complete(fworker.startup())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1424, in _run_once
    handle._run()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 126, in _run
    self._callback(*self._args)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 112, in startup
    await self.register_at_manager(may_retry_loop=may_retry_loop)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 174, in register_at_manager
    self._log.info('Registering at manager')
Message: 'Registering at manager'
Arguments: ()
2017-06-27 06:41:05,303    ERROR flamenco_worker.cli Uncaught exception!
Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 97, in main
    loop.run_until_complete(fworker.startup())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 112, in startup
    await self.register_at_manager(may_retry_loop=may_retry_loop)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 188, in register_at_manager
    may_retry_loop=may_retry_loop,
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 143, in _keep_posting_to_manager
    resp = await self.manager.post(url, **post_kwargs)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\upstream.py", line 28, in post
    return await self.client_request('POST', *args, loop=loop, **kwargs)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\upstream.py", line 86, in client_request
    headers['User-Agent'] = self.user_agent()
TypeError: unhashable type: 'FlamencoManager'
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 97, in main
    loop.run_until_complete(fworker.startup())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 112, in startup
    await self.register_at_manager(may_retry_loop=may_retry_loop)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 188, in register_at_manager
    may_retry_loop=may_retry_loop,
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\worker.py", line 143, in _keep_posting_to_manager
    resp = await self.manager.post(url, **post_kwargs)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\upstream.py", line 28, in post
    return await self.client_request('POST', *args, loop=loop, **kwargs)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\upstream.py", line 86, in client_request
    headers['User-Agent'] = self.user_agent()
TypeError: unhashable type: 'FlamencoManager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1048, in emit
    self.stream = self._open()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\tmp\\flamenco-worker.log'
Call stack:
  File ".\bin\flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 119, in main
    log.exception('Uncaught exception!')
Message: 'Uncaught exception!'
Arguments: ()
2017-06-27 06:41:05,319  WARNING flamenco_worker.cli Closing asyncio loop
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1048, in emit
    self.stream = self._open()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\tmp\\flamenco-worker.log'
Call stack:
  File ".\bin\flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 125, in main
    log.warning('Closing asyncio loop')
Message: 'Closing asyncio loop'
Arguments: ()
2017-06-27 06:41:05,325  WARNING flamenco_worker.cli Flamenco Worker is shut down
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1048, in emit
    self.stream = self._open()
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\tmp\\flamenco-worker.log'
Call stack:
  File ".\bin\flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "C:\Users\shaun\AppData\Local\Programs\Python\Python35\lib\site-packages\flamenco_worker\cli.py", line 127, in main
    log.warning('Flamenco Worker is shut down')
Message: 'Flamenco Worker is shut down'
Arguments: ()

R:\blender\flamenco_v2\worker\worker_dellnavi>

```

**Comment by sybrenstuvel** [comment]
I'll see about running the worker on an actual Windows machine here (it's very, very much untested at the moment, as you've found out).

**Comment by sybrenstuvel** [comment]
I've pushed some Windows-specific changes. Can you try with latest master?

**Comment by mikebellca** [comment]
Well. I _think_ its running. I installed using setup.py from master branch and it did install. I had to create a folder in c:\tmp because it was looking for it for the log file. Once I did that I was able to run the flamenco-worker command and it appears to register with my manager based on my current config. 

I wasn't able to use the blender cloud addon to render that still crashes. 
Is there a simple command line I can run to submit a render job or some kind of command I can see run  without needing the blender cloud addon ?

**Comment by sybrenstuvel** [comment]
> Well. I think its running.

Good. If it is, you should be able to see it on your Manager dashboard. You have completed render jobs in your project, so I guess it worked ;-)

> I wasn't able to use the blender cloud addon to render that still crashes.

I've pushed some Windows-specific fixes to the add-on, so now it works on my Win10 64-bit machine at home.

> Is there a simple command line I can run to submit a render job or some kind of command I can see run without needing the blender cloud addon ?

Yes there is, check out the [CLI client](https://developer.blender.org/diffusion/F/browse/master/clients/cli/blender_render.py) bundled with Flamenco Server.

**Comment by binarypearl** [comment]
I was able to get the worker started in Windows with the new code.  Just like @mikebellca, I had to create C:\tmp .  I think the worker was technically running but it gave pages of stack trace errors until it was created.  Might be best to have it use C:\Temp (at least with windows 10) or use %TEMP%, which should work but would get confusing on where the log file is located at + might be differences between cmd.exe and powershell).

I don't have a video card to put into that Windows computer at the time being (new vid card didn't fit) so I'm not using it right now for rendering.  (I doubled up new vid card in existing linux computer, which is working). 

--Shaun

**Comment by sybrenstuvel** [comment]
> I was able to get the worker started in Windows with the new code. Just like @mikebellca, I had to create C:\tmp .

Yes, this is because of the default location for the log file. You don't have to create C:\tmp, you can also simply configure the worker to log somewhere else. I've added this to the documentation (04ecb9383611a7fbd272cd58cad7d1198dc3dc70).

> I think the worker was technically running but it gave pages of stack trace errors until it was created. Might be best to have it use C:\Temp (at least with windows 10) or use %TEMP%, which should work but would get confusing on where the log file is located at + might be differences between cmd.exe and powershell).

There is no default value that will work on all platforms, and /tmp exists on 2 of the 3 platforms we support. More importantly, the current default works on the platform we actually use ourselves (Linux).

I'm closing this issue, since things seem to be running. If there are other problems, please report it in a new issue.
